---
- name: Create py_env_action_list
  ansible.builtin.set_fact:
    py_env_action_list: "{{ (py_env_actions | default('')).split(',') | reject('equalto', '') | list }}"

- name: Validate py_env_action_list
  ansible.builtin.assert:
    that:
      - py_env_action_list | length > 0
      - py_env_action_list | difference(py_env_supported_actions) | length == 0
    fail_msg: "py_env_actions must be set to one or more of: {{ py_env_supported_actions | join(', ') }}"

- name: Run py_env action
  ansible.builtin.include_tasks: "{{ task_name }}.yml"
  loop: "{{ py_env_action_list }}"
  loop_control:
    loop_var: task_name
