---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        py_env_actions: deploy_envs
        py_env_list:
          /opt/testvenv:
            state: present
            packages:
              - name: pip
                state: present
